import { verifyShareToken } from '@/lib/shareLinks';
import prisma from '@/lib/prisma';
import Link from 'next/link';

export async function generateMetadata() {
  return { robots: 'noindex, nofollow' };
}

export default async function SharePage({ params }: { params: { token: string } }) {
  const link = await verifyShareToken(params.token);

  if (!link) {
    return (
      <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <div style={{ textAlign: 'center', maxWidth: 400 }}>
          <div style={{ fontSize: 48, marginBottom: 16 }}>🔒</div>
          <h1 style={{ fontSize: 20, fontWeight: 700 }}>Link expired or invalid</h1>
          <p style={{ color: 'var(--text-muted)', marginTop: 8 }}>This share link has expired, been revoked, or does not exist.</p>
        </div>
      </div>
    );
  }

  // For now, support task_report entity type
  if (link.entityType !== 'task_report') {
    return <div style={{ padding: 24 }}>Unsupported entity type.</div>;
  }

  const task = await prisma.task.findUnique({
    where: { id: link.entityId },
    include: { project: true, agentRuns: { include: { evaluations: true } }, approval: true },
  });

  if (!task) {
    return <div style={{ padding: 24, color: 'var(--red)' }}>Task not found.</div>;
  }

  return (
    <div style={{ maxWidth: 800, margin: '0 auto', padding: 24 }}>
      {/* No-index header */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 24, padding: '12px 16px', background: 'var(--surface)', borderRadius: 8, border: '1px solid var(--border)' }}>
        <span style={{ fontSize: 20 }}>🔗</span>
        <div>
          <div style={{ fontWeight: 600, fontSize: 14 }}>Shared Report</div>
          <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>Read-only view · Views: {link.viewCount + 1}</div>
        </div>
      </div>

      <h1 style={{ fontSize: 22, fontWeight: 700, marginBottom: 8 }}>{task.title}</h1>
      <div style={{ display: 'flex', gap: 8, marginBottom: 24, flexWrap: 'wrap' }}>
        <span className="badge badge-neutral">{task.status}</span>
        <span className="badge badge-neutral">{task.riskLevel} risk</span>
        <span className="badge badge-neutral">{task.environment}</span>
      </div>

      <div style={{ marginBottom: 24 }}>
        <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 8, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Instruction</div>
        <div style={{ padding: 16, background: 'var(--surface)', borderRadius: 8, border: '1px solid var(--border)', fontSize: 14, lineHeight: 1.6 }}>
          {task.instruction}
        </div>
      </div>

      <div style={{ marginBottom: 24 }}>
        <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 8, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
          Agent Runs ({task.agentRuns.length})
        </div>
        {task.agentRuns.length === 0 ? (
          <div style={{ color: 'var(--text-muted)', fontSize: 13 }}>No runs recorded.</div>
        ) : task.agentRuns.map(run => (
          <div key={run.id} style={{ marginBottom: 12, padding: 12, border: '1px solid var(--border)', borderRadius: 8, background: 'var(--surface)' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8 }}>
              <span className="badge badge-neutral">{run.status}</span>
              <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>{run.startedAt.toISOString().split('T')[0]}</span>
            </div>
            {run.testResult && <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>Test: {run.testResult}</div>}
          </div>
        ))}
      </div>

      <div style={{ padding: 12, background: 'var(--surface)', borderRadius: 6, fontSize: 12, color: 'var(--text-muted)', textAlign: 'center' }}>
        Generated by Coder by DevAscend · Read-only shared view
      </div>
    </div>
  );
}
