import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { generateCsrfToken, validateCsrfToken } from '../csrf.js';

describe('generateCsrfToken', () => {
  test('returns a 64-character hex string', async () => {
    const token = await generateCsrfToken();
    assert.equal(token.length, 64);
    assert.match(token, /^[0-9a-f]{64}$/);
  });

  test('generates unique tokens on successive calls', async () => {
    const a = await generateCsrfToken();
    const b = await generateCsrfToken();
    assert.notEqual(a, b);
  });
});

describe('validateCsrfToken', () => {
  test('returns false when provided is null', () => {
    assert.equal(validateCsrfToken(null, 'abc'), false);
  });

  test('returns false when expected is null', () => {
    assert.equal(validateCsrfToken('abc', null), false);
  });

  test('returns false when expected is undefined', () => {
    assert.equal(validateCsrfToken('abc', undefined), false);
  });

  test('returns true when both values match', () => {
    assert.equal(validateCsrfToken('abc', 'abc'), true);
  });

  test('returns false when values differ', () => {
    assert.equal(validateCsrfToken('abc', 'xyz'), false);
  });

  test('returns false when lengths differ (mismatched lengths)', () => {
    assert.equal(validateCsrfToken('abcd', 'abc'), false);
    assert.equal(validateCsrfToken('abc', 'abcd'), false);
  });

  test('token generated by generateCsrfToken validates against itself', async () => {
    const token = await generateCsrfToken();
    assert.equal(validateCsrfToken(token, token), true);
  });

  test('two different generated tokens do not validate against each other', async () => {
    const a = await generateCsrfToken();
    const b = await generateCsrfToken();
    // Statistically essentially impossible for two random 32-byte tokens to collide
    assert.equal(validateCsrfToken(a, b), false);
  });

  test('returns false when provided is empty string', () => {
    assert.equal(validateCsrfToken('', 'abc'), false);
  });

  test('returns false when expected is empty string', () => {
    assert.equal(validateCsrfToken('abc', ''), false);
  });
});
